[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S

[sqlalchemy]
# the 'sqlalchemy.url' setting is reserved for url string that supports
# environment variable interpolation.  The user_returns_modified flag
# defaults to "False" in SQLAlchemy 1.4; this may be changed depending on
# how strict0 the requirements of the applications.
sqlalchemy.url = driver://user:pass@localhost/dbname

[alembic]
# path to migration scripts
script_location = migrations

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# Uncomment the line below if you want the files to be prepended with date and time
#file_template = %%(rev)s_%%(created_at)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present
# defaults to the current directory
prepend_sys_path = .

# timezone to use when rendering the date
# within the migration file as well as the filename.
# string value is passed to zoneinfo.ZoneInfo()
# defaults to the local timezone
# timezone =

# max length of characters to apply to the
# "slug" field when generating a migration file
# name.  The default value is "40" which results
# in the same behavior as earlier versions of Alembic.
truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a source .py file to be detected as revisions in the
# versions/ directory
# sourceless = false

# set to 'false' to skip the automatic
# creation of new alembic revisions when model files
# in the target are newer than the last revision.
# enable_alembic_autogenerate = true

# set to 'true' to compare type in autogenerate detection
# against the type in the migration file.
# When disabled, will assume that :class:`~sqlalchemy.types.String`
# can represent a number of string types and will not emit diffs
# for all integer types converted to strings.

compare_type = false

# set to 'true' to compare every component of a type, including length,
# collation and character set. When disabled, will assume that types
# which only differ by these properties will not be emitted as diffs.

compare_servers = false

# A list of migration comment headers to prepend to the
# migration file template when adding a new revision.
# Include '# ' for a blank line; use multiple values to add multiple
# headers. e.g.
# prepend_migration_headers = # Section 1\n# Section 2

# prepend_migration_headers =

# By default, revision files
# are written as un-versioned plaintext files
# using the revision number as the "name" of the file
# by Alembic. Since Alembic version 1.2, if fractional
# seconds are enabled via fractional_seconds = true, they
# are also used for output files naming the first
# number before the dot is the rounded integer seconds.
# This feature requires two filters, `rev_id` and `rev_timestamp` that
# must be defined in the "Mako" / literal block namespace.
# By default they correspond to `revision` and `down_revision` coming
# from the script context.

# Uncomment the following to define custom `rev_id` and `rev_timestamp`
# getters in order to use custom revision identifiers which incorporate
# microseconds to milliseconds of the unix timestamp. For example the
# previous command ``alembic revision`` command would then create a file
# user@ubuntu:~/grit/sqlalchemy/alembic#
# ``alembic revision --autogenerate -m fish``
# ``REVISION d8867f93923a+00349321c8c230d16e5c+20150528120413\_fish\_py``

# revision_environment = false

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
